---
# tasks file for deploy_apache_web
- name: Ping my servers
  ping:

- name: Check OS
  debug: var=ansible_os_family

- block: #if OS RedHat
    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Copy MyHomePage to Servers
      template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
      notify: Restart Apache for RedHat
 
    - name: Start WebServer for RedHat and make it enable on boot
      service: name=httpd state=started enabled=yes

    - name: Say Hello to ALL
      debug: msg="Hello {{ item }}"
      loop:
          - "Poxos"
          - "Petros"
          - "Barduximeos"

    - name: Loop Until example
      shell: echo -n Z >> myfile.txt && cat myfile.txt
      register: output
      delay: 2
      retries: 10
      until: output.stdout.find("ZZZZ") == false

    - name: Print Loop output
      debug:
        var: output.stdout

    - name: Install apps with loop
      yum: name={{ item }} state=installed
      with_items:
            - python
            - tree
  when: ansible_os_family == "RedHat"

- block: #if OS Ubuntu
    - name: Install Apache Web Server for Ubuntu
      apt: name=apache2 state=latest

    - name: Copy MyHomePage to Servers
      template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
      notify: Restart Apache for Ubuntu

    - name: Start WebServer for Ubuntu and make it enable on boot
      service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Ubuntu"

#- name: Copy MyHomePage to Servers
#  template: src={{ item }} dest={{ destin_folder }} mode=0555
## template: src={{ item }} dest={{ destin_folder }} mode=0555
##  with_all: "{{ source_folder }}/*,*"
#  loop:
#    - "index.html"
#    - "1.jpg"
#    - "2.jpg"
#    - "3.jpg"
#  notify:
#    - Restart Apache for RedHat
#    - Restart Apache for Ubuntu
